### ISSUE TITLE
Fix bug company upload resolver

### ISSUE THREAD

**Issue by justintunev7** [Career-Launchpad/server#28]
When submitting a new company to the database, the first time "submit" is clicked, nothing happens (really, it just creates the company). The second time submit is clicked, it submits the offer.

This should all happen on the first click.

**Comment by Bobleyl** [comment]
What is happening is when it checks to see if the company exists and it doesn't currently exist in the table it returns saying that the company is "".  However, it also creates the company when it checks, so the next time that you try it the company is there and it works fine.  This is why we have to end up submitting twice when adding an offer using a new company. 

The fix is to simply check and see if the company exists and if not then add it to the Company table and then query again.
